# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9186dc4bcbcfac6634955a5d21f5d1531b8819b7fd01844f42281ca6a8db9a8aa9f12099fdfdd5a219962a1534c560b650885dc34d1bd8f584f3eb1df0f8909f

test:
  secret_key_base: 118bee412b6ea5b01b84d0a4f3b663fe92867b66ed869efa50774159aed0ba7d6d26765648b8f628a10aa802d85ba6dec274efae4445755d1d5e7ffd913006f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 125bee412b6ea5b01b84d0a4f3b663fe92867b66ed869efa50774159aed0ba7d6d26765648b8f628a10aa802d85ba6dec274efae4445755d1d5e7ffd913006f9
